### ISSUE TITLE
Add `.error` class to block for easier visual customization via CSS

### ISSUE THREAD

**Issue by alexandreIFB** [plone/volto#7138]
Add `.error` class to block for easier visual customization via CSS

### Description
It would be useful if the edit block component (`Edit`) added a `.error` CSS class whenever the block has a validation error. This would allow developers and integrators to easily customize the appearance of blocks with errors, for example, highlighting them with a red border or other visual style.

#### Usage example:
With the `.error` class, you could add the following CSS to highlight error blocks:

```css
.block .block.selected.error::before,
.block .block.error::before {
  border-color: #FF0000;
}
```

This approach expands the product's customization possibilities.
